/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "clavesRPC.h"

bool_t
xdr_paquete_rpc (XDR *xdrs, paquete_rpc *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->x))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->y))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->z))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_string (XDR *xdrs, rpc_string *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, RPC_MAX_STR_LEN))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_value2 (XDR *xdrs, rpc_value2 *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->rpc_value2_val, (u_int *) &objp->rpc_value2_len, RPC_MAX_V2_LEN,
		sizeof (float), (xdrproc_t) xdr_float))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_key_request_rpc (XDR *xdrs, key_request_rpc *objp)
{
	register int32_t *buf;

	 if (!xdr_rpc_string (xdrs, &objp->key))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_set_value_request_rpc (XDR *xdrs, set_value_request_rpc *objp)
{
	register int32_t *buf;

	 if (!xdr_rpc_string (xdrs, &objp->key))
		 return FALSE;
	 if (!xdr_rpc_string (xdrs, &objp->value1))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->n_value2))
		 return FALSE;
	 if (!xdr_rpc_value2 (xdrs, &objp->v_value2))
		 return FALSE;
	 if (!xdr_paquete_rpc (xdrs, &objp->value3))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_get_value_response_rpc (XDR *xdrs, get_value_response_rpc *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_rpc_string (xdrs, &objp->value1))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->n_value2))
		 return FALSE;
	 if (!xdr_rpc_value2 (xdrs, &objp->v_value2))
		 return FALSE;
	 if (!xdr_paquete_rpc (xdrs, &objp->value3))
		 return FALSE;
	return TRUE;
}
