/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "clavesRPC.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
destroy_rpc_1(int *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, DESTROY_RPC, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));

}

enum clnt_stat 
set_value_rpc_1(set_value_request_rpc arg1, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, SET_VALUE_RPC,
		(xdrproc_t) xdr_set_value_request_rpc, (caddr_t) &arg1,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
get_value_rpc_1(key_request_rpc arg1, get_value_response_rpc *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, GET_VALUE_RPC,
		(xdrproc_t) xdr_key_request_rpc, (caddr_t) &arg1,
		(xdrproc_t) xdr_get_value_response_rpc, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
modify_value_rpc_1(set_value_request_rpc arg1, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, MODIFY_VALUE_RPC,
		(xdrproc_t) xdr_set_value_request_rpc, (caddr_t) &arg1,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
delete_key_rpc_1(key_request_rpc arg1, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, DELETE_KEY_RPC,
		(xdrproc_t) xdr_key_request_rpc, (caddr_t) &arg1,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
exist_rpc_1(key_request_rpc arg1, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, EXIST_RPC,
		(xdrproc_t) xdr_key_request_rpc, (caddr_t) &arg1,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}
