/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CLAVESRPC_H_RPCGEN
#define _CLAVESRPC_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif

#define RPC_MAX_STR_LEN 255
#define RPC_MAX_V2_LEN 32

struct paquete_rpc {
	int x;
	int y;
	int z;
};
typedef struct paquete_rpc paquete_rpc;

typedef char *rpc_string;

typedef struct {
	u_int rpc_value2_len;
	float *rpc_value2_val;
} rpc_value2;

struct key_request_rpc {
	rpc_string key;
};
typedef struct key_request_rpc key_request_rpc;

struct set_value_request_rpc {
	rpc_string key;
	rpc_string value1;
	int n_value2;
	rpc_value2 v_value2;
	paquete_rpc value3;
};
typedef struct set_value_request_rpc set_value_request_rpc;

struct get_value_response_rpc {
	int status;
	rpc_string value1;
	int n_value2;
	rpc_value2 v_value2;
	paquete_rpc value3;
};
typedef struct get_value_response_rpc get_value_response_rpc;

#define CLAVES_RPC_PROG 0x31234567
#define CLAVES_RPC_V1 1

#if defined(__STDC__) || defined(__cplusplus)
#define DESTROY_RPC 1
extern  enum clnt_stat destroy_rpc_1(int *, CLIENT *);
extern  bool_t destroy_rpc_1_svc(int *, struct svc_req *);
#define SET_VALUE_RPC 2
extern  enum clnt_stat set_value_rpc_1(set_value_request_rpc , int *, CLIENT *);
extern  bool_t set_value_rpc_1_svc(set_value_request_rpc , int *, struct svc_req *);
#define GET_VALUE_RPC 3
extern  enum clnt_stat get_value_rpc_1(key_request_rpc , get_value_response_rpc *, CLIENT *);
extern  bool_t get_value_rpc_1_svc(key_request_rpc , get_value_response_rpc *, struct svc_req *);
#define MODIFY_VALUE_RPC 4
extern  enum clnt_stat modify_value_rpc_1(set_value_request_rpc , int *, CLIENT *);
extern  bool_t modify_value_rpc_1_svc(set_value_request_rpc , int *, struct svc_req *);
#define DELETE_KEY_RPC 5
extern  enum clnt_stat delete_key_rpc_1(key_request_rpc , int *, CLIENT *);
extern  bool_t delete_key_rpc_1_svc(key_request_rpc , int *, struct svc_req *);
#define EXIST_RPC 6
extern  enum clnt_stat exist_rpc_1(key_request_rpc , int *, CLIENT *);
extern  bool_t exist_rpc_1_svc(key_request_rpc , int *, struct svc_req *);
extern int claves_rpc_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define DESTROY_RPC 1
extern  enum clnt_stat destroy_rpc_1();
extern  bool_t destroy_rpc_1_svc();
#define SET_VALUE_RPC 2
extern  enum clnt_stat set_value_rpc_1();
extern  bool_t set_value_rpc_1_svc();
#define GET_VALUE_RPC 3
extern  enum clnt_stat get_value_rpc_1();
extern  bool_t get_value_rpc_1_svc();
#define MODIFY_VALUE_RPC 4
extern  enum clnt_stat modify_value_rpc_1();
extern  bool_t modify_value_rpc_1_svc();
#define DELETE_KEY_RPC 5
extern  enum clnt_stat delete_key_rpc_1();
extern  bool_t delete_key_rpc_1_svc();
#define EXIST_RPC 6
extern  enum clnt_stat exist_rpc_1();
extern  bool_t exist_rpc_1_svc();
extern int claves_rpc_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_paquete_rpc (XDR *, paquete_rpc*);
extern  bool_t xdr_rpc_string (XDR *, rpc_string*);
extern  bool_t xdr_rpc_value2 (XDR *, rpc_value2*);
extern  bool_t xdr_key_request_rpc (XDR *, key_request_rpc*);
extern  bool_t xdr_set_value_request_rpc (XDR *, set_value_request_rpc*);
extern  bool_t xdr_get_value_response_rpc (XDR *, get_value_response_rpc*);

#else /* K&R C */
extern bool_t xdr_paquete_rpc ();
extern bool_t xdr_rpc_string ();
extern bool_t xdr_rpc_value2 ();
extern bool_t xdr_key_request_rpc ();
extern bool_t xdr_set_value_request_rpc ();
extern bool_t xdr_get_value_response_rpc ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CLAVESRPC_H_RPCGEN */
